[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
dialect = "2YFyZAg8rBtuvzFFiGvXwPHFAQJ2FXZoS7bYCKticpjk"

[scripts]
test = "ts-mocha -t 1000000 tests/test-v1.ts"
